#!name=SoundCloud Go+
#!desc=Unlock SoundCloud

[Script]
SoundCloudGo+ = type=http-response,pattern=^https:\/\/api-mobile\.soundcloud\.com\/configuration\/ios,requires-body=1,script-path=https://raw.githubusercontent.com/duyvinh09/Module_IOS/refs/heads/main/js/SoundCloudGoPlus.js

[MITM]
enable = true
hostname = %APPEND% api-mobile.soundcloud.com
